server: 
  port: 8080
spring:
  application:
    name: student-config 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    
eureka:
  client:
    # 指定Eureka服务注册中心
    service-url:
      defaultZone: http://localhost:8000/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
